# Publish GitHub workflow artifacts tutorial example
name: "Check Python code with Bandit"

on: [push, pull_request]

jobs:

  archive-build-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup Dependencies
        run: |
          python -m pip install bandit pylint
      - name: Run lint
        run: |
          pylint sample_python_package

      - name: Create a temporary artifact folder
        run: mkdir artifacts

      - name: Run Bandit
        run: |
          bandit -r sample_python_package -o artifacts/bandit_check.txt -f txt

      - name: Upload Bandit artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bandit-artifacts
          path: artifacts